version: '3'

services:
  db:
    container_name: mysql8
    image: mysql:8.0
    command: mysqld --default-authentication-plugin=caching_sha2_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sandbox
      # MYSQL_USER:
      # MYSQL_PASSWORD:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes' # username and password are root
    ports:
      - '3306:3306'
    volumes:
      - './docker/mysql8/data:/var/lib/mysql'
      - './docker/mysql8/my.cnf:/etc/mysql/conf.d/my.cnf'
      - './docker/mysql8/sql:/docker-entrypoint-initdb.d'
